// wrapTutorial.cpp
// This file is generated by Shroud 0.12.2. Do not edit.

#include "tutorial.hpp"
#include "wrapTutorial.h"

// splicer begin CXX_definitions
// splicer end CXX_definitions

extern "C" {

// splicer begin C_definitions
// splicer end C_definitions

int * TUT_str1_get_iptr(TUT_str1 * SH_this)
{
    // splicer begin function.str1_get_iptr
    str1 * SHCXX_SH_this = static_cast<str1 *>(static_cast<void *>(
        SH_this));
    // skip call c_getter
    return SHCXX_SH_this->iptr;
    // splicer end function.str1_get_iptr
}

void TUT_str1_set_iptr(TUT_str1 * SH_this, int * val)
{
    // splicer begin function.str1_set_iptr
    str1 * SHCXX_SH_this = static_cast<str1 *>(static_cast<void *>(
        SH_this));
    // skip call c_setter
    SHCXX_SH_this->iptr = val;
    // splicer end function.str1_set_iptr
}

double * TUT_str1_get_arr_2d(TUT_str1 * SH_this)
{
    // splicer begin function.str1_get_arr_2d
    str1 * SHCXX_SH_this = static_cast<str1 *>(static_cast<void *>(
        SH_this));
    // skip call c_getter
    return SHCXX_SH_this->arr_2d;
    // splicer end function.str1_get_arr_2d
}

void TUT_str1_set_arr_2d(TUT_str1 * SH_this, double * val)
{
    // splicer begin function.str1_set_arr_2d
    str1 * SHCXX_SH_this = static_cast<str1 *>(static_cast<void *>(
        SH_this));
    // skip call c_setter
    SHCXX_SH_this->arr_2d = val;
    // splicer end function.str1_set_arr_2d
}

}  // extern "C"
