// wrapClass1.h
// This file is generated by Shroud 0.12.2. Do not edit.
/**
 * \file wrapClass1.h
 * \brief Shroud generated wrapper for Class1 class
 */
// For C users and C++ implementation

#ifndef WRAPCLASS1_H
#define WRAPCLASS1_H

#ifndef __cplusplus
#include <stdbool.h>
#endif
#include "typesTutorial.h"

// splicer begin class.Class1.CXX_declarations
#include "wrapTutorial.h"
// splicer end class.Class1.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.Class1.C_declarations
// splicer end class.Class1.C_declarations

TUT_Class1 * TUT_Class1_new_0(int test1, double test2, bool TorF,
    TUT_Class1 * SHC_rv);

TUT_Class1 * TUT_Class1_new_1(int test1, double test2, bool TorF,
    int o_test, TUT_Class1 * SHC_rv);

TUT_Class1 * TUT_Class1_new_2(int test1, double test2, bool TorF,
    int o_test, double o_test2, TUT_Class1 * SHC_rv);

TUT_Class1 * TUT_Class1_new_3(int test1, double test2, bool TorF,
    int o_test, double o_test2, bool o_TorF, TUT_Class1 * SHC_rv);

void TUT_Class1_delete(TUT_Class1 * self);

void TUT_Class1_receive_struct(TUT_Class1 * self, TUT_str1 * arg);

void TUT_Class1_test_struct(TUT_Class1 * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPCLASS1_H
