// wrapTutorial.h
// This file is generated by Shroud 0.12.2. Do not edit.
/**
 * \file wrapTutorial.h
 * \brief Shroud generated wrapper for Tutorial library
 */
// For C users and C++ implementation

#ifndef WRAPTUTORIAL_H
#define WRAPTUTORIAL_H

#include "typesTutorial.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif


struct s_TUT_str1 {
    int ifield;
    double dfield;
    bool ToF;
};
typedef struct s_TUT_str1 TUT_str1;

// splicer begin C_declarations
// splicer end C_declarations

#ifdef __cplusplus
}
#endif

#endif  // WRAPTUTORIAL_H
