! wrapfTutorial_tutorial.F90
! This file is generated by Shroud 0.12.1. Do not edit.
!>
!! \file wrapfTutorial_tutorial.F90
!! \brief Shroud generated wrapper for tutorial namespace
!<
! splicer begin namespace.tutorial.file_top
! splicer end namespace.tutorial.file_top
module tutorial_tutorial_mod
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR
    ! splicer begin namespace.tutorial.module_use
    ! splicer end namespace.tutorial.module_use
    implicit none

    ! splicer begin namespace.tutorial.module_top
    ! splicer end namespace.tutorial.module_top

    type, bind(C) :: SHROUD_class1_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_class1_capsule

    type class1
        type(SHROUD_class1_capsule) :: cxxmem
        ! splicer begin namespace.tutorial.class.Class1.component_part
        ! splicer end namespace.tutorial.class.Class1.component_part
    contains
        procedure :: get_test_ptr => class1_get_test_ptr
        procedure :: get__two_darray_ptr => class1_get__two_darray_ptr
        procedure :: set_test => class1_set_test
        procedure :: set__two_darray => class1_set__two_darray
        procedure :: delete => class1_delete
        procedure :: method1 => class1_method1
        procedure :: accept_char_array_in => class1_accept_char_array_in
        procedure :: get_instance => class1_get_instance
        procedure :: set_instance => class1_set_instance
        procedure :: associated => class1_associated
        ! splicer begin namespace.tutorial.class.Class1.type_bound_procedure_part
        ! splicer end namespace.tutorial.class.Class1.type_bound_procedure_part
    end type class1

    interface operator (.eq.)
        module procedure class1_eq
    end interface

    interface operator (.ne.)
        module procedure class1_ne
    end interface

    interface

        function c_class1_ctor_default(SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_ctor_default")
            use iso_c_binding, only : C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_ctor_default

        function c_class1_get_test_ptr(self, len) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get_test_ptr")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(OUT) :: len
            type(C_PTR) SHT_rv
        end function c_class1_get_test_ptr

        function c_class1_get__two_darray_ptr(self, len1, len2) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get__two_darray_ptr")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(OUT) :: len1
            integer(C_INT), intent(OUT) :: len2
            type(C_PTR) SHT_rv
        end function c_class1_get__two_darray_ptr

        subroutine c_class1_set_test(self, N) &
                bind(C, name="TUT_tutorial_Class1_set_test")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: N
        end subroutine c_class1_set_test

        subroutine c_class1_set__two_darray(self, N, M) &
                bind(C, name="TUT_tutorial_Class1_set__two_darray")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: N
            integer(C_INT), value, intent(IN) :: M
        end subroutine c_class1_set__two_darray

        subroutine c_class1_delete(self) &
                bind(C, name="TUT_tutorial_Class1_delete")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_delete

        subroutine c_class1_method1(self) &
                bind(C, name="TUT_tutorial_Class1_method1")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_method1

        subroutine c_class1_accept_char_array_in(self, names, clsize) &
                bind(C, name="TUT_tutorial_Class1_accept_char_array_in")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(IN) :: names(*)
            integer(C_INT), value, intent(IN) :: clsize
        end subroutine c_class1_accept_char_array_in

        subroutine c_class1_accept_char_array_in_bufferify(self, names, &
                Snames, Nnames, clsize) &
                bind(C, name="TUT_tutorial_Class1_accept_char_array_in_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT, C_LONG
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(IN) :: names(*)
            integer(C_LONG), value, intent(IN) :: Snames
            integer(C_INT), value, intent(IN) :: Nnames
            integer(C_INT), value, intent(IN) :: clsize
        end subroutine c_class1_accept_char_array_in_bufferify

        ! splicer begin namespace.tutorial.class.Class1.additional_interfaces
        ! splicer end namespace.tutorial.class.Class1.additional_interfaces

        ! splicer begin namespace.tutorial.additional_interfaces
        ! splicer end namespace.tutorial.additional_interfaces
    end interface

    interface class1
        module procedure class1_ctor_default
    end interface class1

contains

    function class1_ctor_default() &
            result(SHT_rv)
        use iso_c_binding, only : C_PTR
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.ctor_default
        type(C_PTR) :: SHT_prv
        SHT_prv = c_class1_ctor_default(SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.ctor_default
    end function class1_ctor_default

    function class1_get_test_ptr(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT, C_PTR, c_f_pointer
        class(class1) :: obj
        integer(C_INT) :: len
        integer(C_INT), pointer :: SHT_rv(:)
        ! splicer begin namespace.tutorial.class.Class1.method.get_test_ptr
        type(C_PTR) :: SHT_ptr
        SHT_ptr = c_class1_get_test_ptr(obj%cxxmem, len)
        call c_f_pointer(SHT_ptr, SHT_rv, [len])
        ! splicer end namespace.tutorial.class.Class1.method.get_test_ptr
    end function class1_get_test_ptr

    function class1_get__two_darray_ptr(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT, C_PTR, c_f_pointer
        class(class1) :: obj
        integer(C_INT) :: len1
        integer(C_INT) :: len2
        integer(C_INT), pointer :: SHT_rv(:,:)
        ! splicer begin namespace.tutorial.class.Class1.method.get__two_darray_ptr
        type(C_PTR) :: SHT_ptr
        SHT_ptr = c_class1_get__two_darray_ptr(obj%cxxmem, len1, len2)
        call c_f_pointer(SHT_ptr, SHT_rv, [len1,len2])
        ! splicer end namespace.tutorial.class.Class1.method.get__two_darray_ptr
    end function class1_get__two_darray_ptr

    subroutine class1_set_test(obj, N)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), value, intent(IN) :: N
        ! splicer begin namespace.tutorial.class.Class1.method.set_test
        call c_class1_set_test(obj%cxxmem, N)
        ! splicer end namespace.tutorial.class.Class1.method.set_test
    end subroutine class1_set_test

    subroutine class1_set__two_darray(obj, N, M)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), value, intent(IN) :: N
        integer(C_INT), value, intent(IN) :: M
        ! splicer begin namespace.tutorial.class.Class1.method.set__two_darray
        call c_class1_set__two_darray(obj%cxxmem, N, M)
        ! splicer end namespace.tutorial.class.Class1.method.set__two_darray
    end subroutine class1_set__two_darray

    subroutine class1_delete(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.delete
        call c_class1_delete(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.delete
    end subroutine class1_delete

    subroutine class1_method1(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.method1
        call c_class1_method1(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.method1
    end subroutine class1_method1

    subroutine class1_accept_char_array_in(obj, names)
        use iso_c_binding, only : C_INT, C_LONG
        class(class1) :: obj
        character(len=*), intent(IN) :: names(:)
        integer(C_INT) :: clsize
        ! splicer begin namespace.tutorial.class.Class1.method.accept_char_array_in
        clsize = size(names)
        call c_class1_accept_char_array_in_bufferify(obj%cxxmem, names, &
        size(names, kind=C_LONG), len(names, kind=C_INT), clsize)
        ! splicer end namespace.tutorial.class.Class1.method.accept_char_array_in
    end subroutine class1_accept_char_array_in

    ! Return pointer to C++ memory.
    function class1_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(class1), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function class1_get_instance

    subroutine class1_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(class1), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine class1_set_instance

    function class1_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(class1), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function class1_associated

    ! splicer begin namespace.tutorial.class.Class1.additional_functions
    ! splicer end namespace.tutorial.class.Class1.additional_functions

    ! splicer begin namespace.tutorial.additional_functions
    ! splicer end namespace.tutorial.additional_functions

    function class1_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_eq

    function class1_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_ne

end module tutorial_tutorial_mod
