! wrapfTutorial_tutorial.F90
! This file is generated by Shroud 0.12.1. Do not edit.
!>
!! \file wrapfTutorial_tutorial.F90
!! \brief Shroud generated wrapper for tutorial namespace
!<
! splicer begin namespace.tutorial.file_top
! splicer end namespace.tutorial.file_top
module tutorial_tutorial_mod
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR
    ! splicer begin namespace.tutorial.module_use
    ! splicer end namespace.tutorial.module_use
    implicit none

    ! splicer begin namespace.tutorial.module_top
    ! splicer end namespace.tutorial.module_top

    type, bind(C) :: SHROUD_class1_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_class1_capsule

    type class1
        type(SHROUD_class1_capsule) :: cxxmem
        ! splicer begin namespace.tutorial.class.Class1.component_part
        ! splicer end namespace.tutorial.class.Class1.component_part
    contains
        procedure :: get_test_ptr => class1_get_test_ptr
        procedure :: get__two_darray_ptr => class1_get__two_darray_ptr
        procedure :: set_test => class1_set_test
        procedure :: set__two_darray => class1_set__two_darray
        procedure :: delete => class1_delete
        procedure :: method1_0 => class1_method1_0
        procedure :: method1_1 => class1_method1_1
        procedure :: method1_2 => class1_method1_2
        procedure :: method1_3 => class1_method1_3
        procedure :: method1_4 => class1_method1_4
        procedure :: accept_char_array_in => class1_accept_char_array_in
        procedure :: check => class1_check
        procedure :: get_dk => class1_get_dk
        procedure :: get_instance => class1_get_instance
        procedure :: set_instance => class1_set_instance
        procedure :: associated => class1_associated
        generic :: method1 => method1_0, method1_1, method1_2, method1_3 &
            , method1_4
        ! splicer begin namespace.tutorial.class.Class1.type_bound_procedure_part
        ! splicer end namespace.tutorial.class.Class1.type_bound_procedure_part
    end type class1

    interface operator (.eq.)
        module procedure class1_eq
    end interface

    interface operator (.ne.)
        module procedure class1_ne
    end interface

    interface

        function c_class1_new_0(test1, test2, TorF, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_0")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_0

        function c_class1_new_1(test1, test2, TorF, o_test, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_1")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_1

        function c_class1_new_2(test1, test2, TorF, o_test, o_test2, &
                SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_2")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            real(C_DOUBLE), value, intent(IN) :: o_test2
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_2

        function c_class1_new_3(test1, test2, TorF, o_test, o_test2, &
                o_TorF, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_3")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            real(C_DOUBLE), value, intent(IN) :: o_test2
            logical(C_BOOL), value, intent(IN) :: o_TorF
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_3

        function c_class1_get_test_ptr(self, len) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get_test_ptr")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(OUT) :: len
            type(C_PTR) SHT_rv
        end function c_class1_get_test_ptr

        function c_class1_get__two_darray_ptr(self, len1, len2) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get__two_darray_ptr")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(OUT) :: len1
            integer(C_INT), intent(OUT) :: len2
            type(C_PTR) SHT_rv
        end function c_class1_get__two_darray_ptr

        subroutine c_class1_set_test(self, N) &
                bind(C, name="TUT_tutorial_Class1_set_test")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: N
        end subroutine c_class1_set_test

        subroutine c_class1_set__two_darray(self, N, M) &
                bind(C, name="TUT_tutorial_Class1_set__two_darray")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: N
            integer(C_INT), value, intent(IN) :: M
        end subroutine c_class1_set__two_darray

        subroutine c_class1_delete(self) &
                bind(C, name="TUT_tutorial_Class1_delete")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_delete

        subroutine c_class1_method1_0(self, vec2d) &
                bind(C, name="TUT_tutorial_Class1_method1_0")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
        end subroutine c_class1_method1_0

        subroutine c_class1_method1_1(self, vec2d, o_test) &
                bind(C, name="TUT_tutorial_Class1_method1_1")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
        end subroutine c_class1_method1_1

        subroutine c_class1_method1_2(self, vec2d, o_test, value) &
                bind(C, name="TUT_tutorial_Class1_method1_2")
            use iso_c_binding, only : C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
            integer(C_INT), intent(INOUT) :: value(*)
        end subroutine c_class1_method1_2

        subroutine c_class1_method1_3(self, vec2d, o_test, value, word2) &
                bind(C, name="TUT_tutorial_Class1_method1_3")
            use iso_c_binding, only : C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
            integer(C_INT), intent(INOUT) :: value(*)
            character(kind=C_CHAR), intent(INOUT) :: word2(*)
        end subroutine c_class1_method1_3

        subroutine c_class1_method1_3_bufferify(self, vec2d, o_test, &
                value, word2, Lword2, Nword2) &
                bind(C, name="TUT_tutorial_Class1_method1_3_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
            integer(C_INT), intent(INOUT) :: value(*)
            character(kind=C_CHAR), intent(INOUT) :: word2(*)
            integer(C_INT), value, intent(IN) :: Lword2
            integer(C_INT), value, intent(IN) :: Nword2
        end subroutine c_class1_method1_3_bufferify

        subroutine c_class1_method1_4(self, vec2d, o_test, value, word2, &
                o_bool) &
                bind(C, name="TUT_tutorial_Class1_method1_4")
            use iso_c_binding, only : C_BOOL, C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
            integer(C_INT), intent(INOUT) :: value(*)
            character(kind=C_CHAR), intent(INOUT) :: word2(*)
            logical(C_BOOL), value, intent(IN) :: o_bool
        end subroutine c_class1_method1_4

        subroutine c_class1_method1_4_bufferify(self, vec2d, o_test, &
                value, word2, Lword2, Nword2, o_bool) &
                bind(C, name="TUT_tutorial_Class1_method1_4_bufferify")
            use iso_c_binding, only : C_BOOL, C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(INOUT) :: vec2d(*)
            integer(C_INT), value, intent(IN) :: o_test
            integer(C_INT), intent(INOUT) :: value(*)
            character(kind=C_CHAR), intent(INOUT) :: word2(*)
            integer(C_INT), value, intent(IN) :: Lword2
            integer(C_INT), value, intent(IN) :: Nword2
            logical(C_BOOL), value, intent(IN) :: o_bool
        end subroutine c_class1_method1_4_bufferify

        subroutine c_class1_accept_char_array_in(self, names, clsize) &
                bind(C, name="TUT_tutorial_Class1_accept_char_array_in")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(IN) :: names(*)
            integer(C_INT), value, intent(IN) :: clsize
        end subroutine c_class1_accept_char_array_in

        subroutine c_class1_accept_char_array_in_bufferify(self, names, &
                Snames, Nnames, clsize) &
                bind(C, name="TUT_tutorial_Class1_accept_char_array_in_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT, C_LONG
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(IN) :: names(*)
            integer(C_LONG), value, intent(IN) :: Snames
            integer(C_INT), value, intent(IN) :: Nnames
            integer(C_INT), value, intent(IN) :: clsize
        end subroutine c_class1_accept_char_array_in_bufferify

        function c_class1_check(self, N) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_check")
            use iso_c_binding, only : C_BOOL, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: N
            logical(C_BOOL) :: SHT_rv
        end function c_class1_check

        function c_class1_get_dk(self) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get_dk")
            use iso_c_binding, only : C_DOUBLE
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            real(C_DOUBLE) :: SHT_rv
        end function c_class1_get_dk

        ! splicer begin namespace.tutorial.class.Class1.additional_interfaces
        ! splicer end namespace.tutorial.class.Class1.additional_interfaces

        ! splicer begin namespace.tutorial.additional_interfaces
        ! splicer end namespace.tutorial.additional_interfaces
    end interface

    interface class1
        module procedure class1_new_0
        module procedure class1_new_1
        module procedure class1_new_2
        module procedure class1_new_3
    end interface class1

contains

    function class1_new_0(test1, test2, TorF) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_0
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_0(test1, test2, SH_TorF, SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_0
    end function class1_new_0

    function class1_new_1(test1, test2, TorF, o_test) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_1
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_1(test1, test2, SH_TorF, o_test, &
            SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_1
    end function class1_new_1

    function class1_new_2(test1, test2, TorF, o_test, o_test2) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        real(C_DOUBLE), value, intent(IN) :: o_test2
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_2
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_2(test1, test2, SH_TorF, o_test, o_test2, &
            SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_2
    end function class1_new_2

    function class1_new_3(test1, test2, TorF, o_test, o_test2, o_TorF) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        real(C_DOUBLE), value, intent(IN) :: o_test2
        logical, value, intent(IN) :: o_TorF
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_3
        logical(C_BOOL) SH_TorF
        logical(C_BOOL) SH_o_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SH_o_TorF = o_TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_3(test1, test2, SH_TorF, o_test, o_test2, &
            SH_o_TorF, SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_3
    end function class1_new_3

    function class1_get_test_ptr(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT, C_PTR, c_f_pointer
        class(class1) :: obj
        integer(C_INT) :: len
        integer(C_INT), pointer :: SHT_rv(:)
        ! splicer begin namespace.tutorial.class.Class1.method.get_test_ptr
        type(C_PTR) :: SHT_ptr
        SHT_ptr = c_class1_get_test_ptr(obj%cxxmem, len)
        call c_f_pointer(SHT_ptr, SHT_rv, [len])
        ! splicer end namespace.tutorial.class.Class1.method.get_test_ptr
    end function class1_get_test_ptr

    function class1_get__two_darray_ptr(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT, C_PTR, c_f_pointer
        class(class1) :: obj
        integer(C_INT) :: len1
        integer(C_INT) :: len2
        integer(C_INT), pointer :: SHT_rv(:,:)
        ! splicer begin namespace.tutorial.class.Class1.method.get__two_darray_ptr
        type(C_PTR) :: SHT_ptr
        SHT_ptr = c_class1_get__two_darray_ptr(obj%cxxmem, len1, len2)
        call c_f_pointer(SHT_ptr, SHT_rv, [len1,len2])
        ! splicer end namespace.tutorial.class.Class1.method.get__two_darray_ptr
    end function class1_get__two_darray_ptr

    subroutine class1_set_test(obj, N)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), value, intent(IN) :: N
        ! splicer begin namespace.tutorial.class.Class1.method.set_test
        call c_class1_set_test(obj%cxxmem, N)
        ! splicer end namespace.tutorial.class.Class1.method.set_test
    end subroutine class1_set_test

    subroutine class1_set__two_darray(obj, N, M)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), value, intent(IN) :: N
        integer(C_INT), value, intent(IN) :: M
        ! splicer begin namespace.tutorial.class.Class1.method.set__two_darray
        call c_class1_set__two_darray(obj%cxxmem, N, M)
        ! splicer end namespace.tutorial.class.Class1.method.set__two_darray
    end subroutine class1_set__two_darray

    subroutine class1_delete(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.delete
        call c_class1_delete(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.delete
    end subroutine class1_delete

    subroutine class1_method1_0(obj, vec2d)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), intent(INOUT) :: vec2d(:,:)
        ! splicer begin namespace.tutorial.class.Class1.method.method1_0
        call c_class1_method1_0(obj%cxxmem, vec2d)
        ! splicer end namespace.tutorial.class.Class1.method.method1_0
    end subroutine class1_method1_0

    subroutine class1_method1_1(obj, vec2d, o_test)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), intent(INOUT) :: vec2d(:,:)
        integer(C_INT), value, intent(IN) :: o_test
        ! splicer begin namespace.tutorial.class.Class1.method.method1_1
        call c_class1_method1_1(obj%cxxmem, vec2d, o_test)
        ! splicer end namespace.tutorial.class.Class1.method.method1_1
    end subroutine class1_method1_1

    subroutine class1_method1_2(obj, vec2d, o_test, value)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), intent(INOUT) :: vec2d(:,:)
        integer(C_INT), value, intent(IN) :: o_test
        integer(C_INT), intent(INOUT) :: value(:)
        ! splicer begin namespace.tutorial.class.Class1.method.method1_2
        call c_class1_method1_2(obj%cxxmem, vec2d, o_test, value)
        ! splicer end namespace.tutorial.class.Class1.method.method1_2
    end subroutine class1_method1_2

    subroutine class1_method1_3(obj, vec2d, o_test, value, word2)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        integer(C_INT), intent(INOUT) :: vec2d(:,:)
        integer(C_INT), value, intent(IN) :: o_test
        integer(C_INT), intent(INOUT) :: value(:)
        character(len=*), intent(INOUT) :: word2
        ! splicer begin namespace.tutorial.class.Class1.method.method1_3
        call c_class1_method1_3_bufferify(obj%cxxmem, vec2d, o_test, &
            value, word2, len_trim(word2, kind=C_INT), &
            len(word2, kind=C_INT))
        ! splicer end namespace.tutorial.class.Class1.method.method1_3
    end subroutine class1_method1_3

    subroutine class1_method1_4(obj, vec2d, o_test, value, word2, &
            o_bool)
        use iso_c_binding, only : C_BOOL, C_INT
        class(class1) :: obj
        integer(C_INT), intent(INOUT) :: vec2d(:,:)
        integer(C_INT), value, intent(IN) :: o_test
        integer(C_INT), intent(INOUT) :: value(:)
        character(len=*), intent(INOUT) :: word2
        logical, value, intent(IN) :: o_bool
        ! splicer begin namespace.tutorial.class.Class1.method.method1_4
        logical(C_BOOL) SH_o_bool
        SH_o_bool = o_bool  ! coerce to C_BOOL
        call c_class1_method1_4_bufferify(obj%cxxmem, vec2d, o_test, &
            value, word2, len_trim(word2, kind=C_INT), &
            len(word2, kind=C_INT), SH_o_bool)
        ! splicer end namespace.tutorial.class.Class1.method.method1_4
    end subroutine class1_method1_4

    subroutine class1_accept_char_array_in(obj, names)
        use iso_c_binding, only : C_INT, C_LONG
        class(class1) :: obj
        character(len=*), intent(IN) :: names(:)
        integer(C_INT) :: clsize
        ! splicer begin namespace.tutorial.class.Class1.method.accept_char_array_in
        clsize = size(names)
        call c_class1_accept_char_array_in_bufferify(obj%cxxmem, names, &
        size(names, kind=C_LONG), len(names, kind=C_INT), clsize)
        ! splicer end namespace.tutorial.class.Class1.method.accept_char_array_in
    end subroutine class1_accept_char_array_in

    function class1_check(obj, N) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_INT
        class(class1) :: obj
        integer(C_INT), value, intent(IN) :: N
        logical :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.check
        SHT_rv = c_class1_check(obj%cxxmem, N)
        ! splicer end namespace.tutorial.class.Class1.method.check
    end function class1_check

    function class1_get_dk(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_DOUBLE
        class(class1) :: obj
        real(C_DOUBLE) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.get_dk
        SHT_rv = c_class1_get_dk(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.get_dk
    end function class1_get_dk

    ! Return pointer to C++ memory.
    function class1_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(class1), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function class1_get_instance

    subroutine class1_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(class1), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine class1_set_instance

    function class1_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(class1), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function class1_associated

    ! splicer begin namespace.tutorial.class.Class1.additional_functions
    ! splicer end namespace.tutorial.class.Class1.additional_functions

    ! splicer begin namespace.tutorial.additional_functions
    ! splicer end namespace.tutorial.additional_functions

    function class1_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_eq

    function class1_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_ne

end module tutorial_tutorial_mod
