// wrapTutorial_tutorial.h
// This file is generated by Shroud 0.12.1. Do not edit.
/**
 * \file wrapTutorial_tutorial.h
 * \brief Shroud generated wrapper for tutorial namespace
 */
// For C users and C++ implementation

#ifndef WRAPTUTORIAL_TUTORIAL_H
#define WRAPTUTORIAL_TUTORIAL_H

#include "typesTutorial.h"

// splicer begin namespace.tutorial.CXX_declarations
// splicer end namespace.tutorial.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif


struct s_TUT_str1 {
    int ifield;
    double dfield;
    int * iptr;
    const char * names;
    bool ToF;
    double * arr_2d;
};
typedef struct s_TUT_str1 TUT_str1;

// splicer begin namespace.tutorial.C_declarations
// splicer end namespace.tutorial.C_declarations

#ifdef __cplusplus
}
#endif

#endif  // WRAPTUTORIAL_TUTORIAL_H
