! wrapfTutorial_tutorial.F90
! This file is generated by Shroud 0.12.1. Do not edit.
!>
!! \file wrapfTutorial_tutorial.F90
!! \brief Shroud generated wrapper for tutorial namespace
!<
! splicer begin namespace.tutorial.file_top
! splicer end namespace.tutorial.file_top
module tutorial_tutorial_mod
    use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_NULL_PTR, C_PTR
    ! splicer begin namespace.tutorial.module_use
    ! splicer end namespace.tutorial.module_use
    implicit none

    ! splicer begin namespace.tutorial.module_top
    ! splicer end namespace.tutorial.module_top

    type, bind(C) :: SHROUD_class1_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_class1_capsule

    type class1
        type(SHROUD_class1_capsule) :: cxxmem
        ! splicer begin namespace.tutorial.class.Class1.component_part
        ! splicer end namespace.tutorial.class.Class1.component_part
    contains
        procedure :: delete => class1_delete
        procedure :: receive_str => class1_receive_str
        procedure :: set_names => class1_set_names
        procedure :: set_names2 => class1_set_names2
        procedure :: test_names2 => class1_test_names2
        procedure :: get_name => class1_get_name
        procedure :: get_name2 => class1_get_name2
        procedure :: test_struct => class1_test_struct
        procedure :: get_instance => class1_get_instance
        procedure :: set_instance => class1_set_instance
        procedure :: associated => class1_associated
        ! splicer begin namespace.tutorial.class.Class1.type_bound_procedure_part
        ! splicer end namespace.tutorial.class.Class1.type_bound_procedure_part
    end type class1


    ! start derived-type str1
    type, bind(C) :: str1
        integer(C_INT) :: ifield
        real(C_DOUBLE) :: dfield
        type(C_PTR) :: iptr
        type(C_PTR) :: names
        logical :: ToF
        type(C_PTR) :: arr_2d
    end type str1
    ! end derived-type str1

    interface operator (.eq.)
        module procedure class1_eq
    end interface

    interface operator (.ne.)
        module procedure class1_ne
    end interface

    interface

        function c_class1_new_0(test1, test2, TorF, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_0")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_0

        function c_class1_new_1(test1, test2, TorF, o_test, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_1")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_1

        function c_class1_new_2(test1, test2, TorF, o_test, o_test2, &
                SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_2")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            real(C_DOUBLE), value, intent(IN) :: o_test2
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_2

        function c_class1_new_3(test1, test2, TorF, o_test, o_test2, &
                o_TorF, SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new_3")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            integer(C_INT), value, intent(IN) :: test1
            real(C_DOUBLE), value, intent(IN) :: test2
            logical(C_BOOL), value, intent(IN) :: TorF
            integer(C_INT), value, intent(IN) :: o_test
            real(C_DOUBLE), value, intent(IN) :: o_test2
            logical(C_BOOL), value, intent(IN) :: o_TorF
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new_3

        subroutine c_class1_delete(self) &
                bind(C, name="TUT_tutorial_Class1_delete")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_delete

        subroutine c_class1_receive_str(self, arg) &
                bind(C, name="TUT_tutorial_Class1_receive_str")
            import :: SHROUD_class1_capsule, str1
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(str1), intent(INOUT) :: arg
        end subroutine c_class1_receive_str

        subroutine c_class1_set_names(self, names, name_len) &
                bind(C, name="TUT_tutorial_Class1_set_names")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(IN) :: names(*)
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_set_names

        subroutine c_class1_set_names_bufferify(self, names, Snames, &
                Nnames, name_len) &
                bind(C, name="TUT_tutorial_Class1_set_names_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT, C_LONG
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(IN) :: names(*)
            integer(C_LONG), value, intent(IN) :: Snames
            integer(C_INT), value, intent(IN) :: Nnames
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_set_names_bufferify

        subroutine c_class1_set_names2(self, names, name_len) &
                bind(C, name="TUT_tutorial_Class1_set_names2")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(IN) :: names(*)
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_set_names2

        subroutine c_class1_set_names2_bufferify(self, names, Snames, &
                Nnames, name_len) &
                bind(C, name="TUT_tutorial_Class1_set_names2_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT, C_LONG
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(IN) :: names(*)
            integer(C_LONG), value, intent(IN) :: Snames
            integer(C_INT), value, intent(IN) :: Nnames
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_set_names2_bufferify

        subroutine c_class1_test_names2(self) &
                bind(C, name="TUT_tutorial_Class1_test_names2")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_test_names2

        subroutine c_class1_get_name(self, name_list, idx) &
                bind(C, name="TUT_tutorial_Class1_get_name")
            use iso_c_binding, only : C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(OUT) :: name_list(*)
            integer(C_INT), value, intent(IN) :: idx
        end subroutine c_class1_get_name

        subroutine c_class1_get_name_bufferify(self, name_list, &
                Nname_list, idx) &
                bind(C, name="TUT_tutorial_Class1_get_name_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            character(kind=C_CHAR), intent(OUT) :: name_list(*)
            integer(C_INT), value, intent(IN) :: Nname_list
            integer(C_INT), value, intent(IN) :: idx
        end subroutine c_class1_get_name_bufferify

        subroutine c_class1_get_name2(self, names, name_len) &
                bind(C, name="TUT_tutorial_Class1_get_name2")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(INOUT) :: names
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_get_name2

        subroutine c_class1_get_name2_bufferify(self, names, name_len) &
                bind(C, name="TUT_tutorial_Class1_get_name2_bufferify")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(INOUT) :: names
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_get_name2_bufferify

        subroutine c_class1_test_struct(self) &
                bind(C, name="TUT_tutorial_Class1_test_struct")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_test_struct

        ! splicer begin namespace.tutorial.class.Class1.additional_interfaces
        ! splicer end namespace.tutorial.class.Class1.additional_interfaces

        ! splicer begin namespace.tutorial.additional_interfaces
        ! splicer end namespace.tutorial.additional_interfaces
    end interface

    interface class1
        module procedure class1_new_0
        module procedure class1_new_1
        module procedure class1_new_2
        module procedure class1_new_3
    end interface class1

contains

    function class1_new_0(test1, test2, TorF) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_0
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_0(test1, test2, SH_TorF, SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_0
    end function class1_new_0

    function class1_new_1(test1, test2, TorF, o_test) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_1
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_1(test1, test2, SH_TorF, o_test, &
            SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_1
    end function class1_new_1

    function class1_new_2(test1, test2, TorF, o_test, o_test2) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        real(C_DOUBLE), value, intent(IN) :: o_test2
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_2
        logical(C_BOOL) SH_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_2(test1, test2, SH_TorF, o_test, o_test2, &
            SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_2
    end function class1_new_2

    function class1_new_3(test1, test2, TorF, o_test, o_test2, o_TorF) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_PTR
        integer(C_INT), value, intent(IN) :: test1
        real(C_DOUBLE), value, intent(IN) :: test2
        logical, value, intent(IN) :: TorF
        integer(C_INT), value, intent(IN) :: o_test
        real(C_DOUBLE), value, intent(IN) :: o_test2
        logical, value, intent(IN) :: o_TorF
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new_3
        logical(C_BOOL) SH_TorF
        logical(C_BOOL) SH_o_TorF
        type(C_PTR) :: SHT_prv
        SH_TorF = TorF  ! coerce to C_BOOL
        SH_o_TorF = o_TorF  ! coerce to C_BOOL
        SHT_prv = c_class1_new_3(test1, test2, SH_TorF, o_test, o_test2, &
            SH_o_TorF, SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new_3
    end function class1_new_3

    subroutine class1_delete(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.delete
        call c_class1_delete(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.delete
    end subroutine class1_delete

    subroutine class1_receive_str(obj, arg)
        class(class1) :: obj
        type(str1), intent(INOUT) :: arg
        ! splicer begin namespace.tutorial.class.Class1.method.receive_str
        call c_class1_receive_str(obj%cxxmem, arg)
        ! splicer end namespace.tutorial.class.Class1.method.receive_str
    end subroutine class1_receive_str

    subroutine class1_set_names(obj, names)
        use iso_c_binding, only : C_INT, C_LONG
        class(class1) :: obj
        character(len=*), intent(IN) :: names(:)
        integer(C_INT) :: name_len
        ! splicer begin namespace.tutorial.class.Class1.method.set_names
        call c_class1_set_names_bufferify(obj%cxxmem, names, &
            size(names, kind=C_LONG), len(names, kind=C_INT), name_len)
        ! splicer end namespace.tutorial.class.Class1.method.set_names
    end subroutine class1_set_names

    subroutine class1_set_names2(obj, names)
        use iso_c_binding, only : C_INT, C_LONG
        class(class1) :: obj
        character(len=*), intent(IN) :: names(:)
        integer(C_INT) :: name_len
        ! splicer begin namespace.tutorial.class.Class1.method.set_names2
        call c_class1_set_names2_bufferify(obj%cxxmem, names, &
            size(names, kind=C_LONG), len(names, kind=C_INT), name_len)
        ! splicer end namespace.tutorial.class.Class1.method.set_names2
    end subroutine class1_set_names2

    subroutine class1_test_names2(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.test_names2
        call c_class1_test_names2(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.test_names2
    end subroutine class1_test_names2

    subroutine class1_get_name(obj, name_list, idx)
        use iso_c_binding, only : C_INT
        class(class1) :: obj
        character(len=*), intent(OUT) :: name_list
        integer(C_INT), value, intent(IN) :: idx
        ! splicer begin namespace.tutorial.class.Class1.method.get_name
        call c_class1_get_name_bufferify(obj%cxxmem, name_list, &
            len(name_list, kind=C_INT), idx)
        ! splicer end namespace.tutorial.class.Class1.method.get_name
    end subroutine class1_get_name

    subroutine class1_get_name2(obj, names)
        use iso_c_binding, only : C_F_POINTER, C_INT, C_LOC
        class(class1) :: obj
        character(len=*), intent(INOUT), pointer :: names(:)
        integer(C_INT) :: name_len
        ! splicer begin namespace.tutorial.class.Class1.method.get_name2
        type(C_PTR) names_Cptr
        names_Cptr = C_LOC(names)
        call c_class1_get_name2_bufferify(obj%cxxmem, names_Cptr, name_len)
        call C_F_POINTER(names_Cptr,names,[name_len])
        ! splicer end namespace.tutorial.class.Class1.method.get_name2
    end subroutine class1_get_name2

    subroutine class1_test_struct(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.test_struct
        call c_class1_test_struct(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.test_struct
    end subroutine class1_test_struct

    ! Return pointer to C++ memory.
    function class1_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(class1), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function class1_get_instance

    subroutine class1_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(class1), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine class1_set_instance

    function class1_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(class1), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function class1_associated

    ! splicer begin namespace.tutorial.class.Class1.additional_functions
    ! splicer end namespace.tutorial.class.Class1.additional_functions

    ! splicer begin namespace.tutorial.additional_functions
    ! splicer end namespace.tutorial.additional_functions

    function class1_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_eq

    function class1_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_ne

end module tutorial_tutorial_mod
