! wrapfTutorial_tutorial.F90
! This file is generated by Shroud 0.12.1. Do not edit.
!>
!! \file wrapfTutorial_tutorial.F90
!! \brief Shroud generated wrapper for tutorial namespace
!<
! splicer begin namespace.tutorial.file_top
! splicer end namespace.tutorial.file_top
module tutorial_tutorial_mod
    use iso_c_binding, only : C_INT, C_LONG, C_NULL_PTR, C_PTR, C_SIZE_T
    ! splicer begin namespace.tutorial.module_use
    ! splicer end namespace.tutorial.module_use
    implicit none

    ! splicer begin namespace.tutorial.module_top
    ! splicer end namespace.tutorial.module_top

    ! helper capsule_data_helper
    type, bind(C) :: SHROUD_capsule_data
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_capsule_data

    ! helper array_context
    type, bind(C) :: SHROUD_array
        ! address of C++ memory
        type(SHROUD_capsule_data) :: cxx
        ! address of data in cxx
        type(C_PTR) :: base_addr = C_NULL_PTR
        ! type of element
        integer(C_INT) :: type
        ! bytes-per-item or character len of data in cxx
        integer(C_SIZE_T) :: elem_len = 0_C_SIZE_T
        ! size of data in cxx
        integer(C_SIZE_T) :: size = 0_C_SIZE_T
        ! number of dimensions
        integer(C_INT) :: rank = -1
        integer(C_LONG) :: shape(7) = 0
    end type SHROUD_array

    type, bind(C) :: SHROUD_class1_capsule
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type SHROUD_class1_capsule

    type class1
        type(SHROUD_class1_capsule) :: cxxmem
        ! splicer begin namespace.tutorial.class.Class1.component_part
        ! splicer end namespace.tutorial.class.Class1.component_part
    contains
        procedure :: set_strings => class1_set_strings
        procedure :: printvalues => class1_printvalues
        procedure :: get_int_ptr => class1_get_int_ptr
        procedure :: get_strs => class1_get_strs
        procedure :: delete => class1_delete
        procedure :: get_instance => class1_get_instance
        procedure :: set_instance => class1_set_instance
        procedure :: associated => class1_associated
        ! splicer begin namespace.tutorial.class.Class1.type_bound_procedure_part
        ! splicer end namespace.tutorial.class.Class1.type_bound_procedure_part
    end type class1

    interface operator (.eq.)
        module procedure class1_eq
    end interface

    interface operator (.ne.)
        module procedure class1_ne
    end interface

    interface

        function c_class1_new(SHT_crv) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_new")
            use iso_c_binding, only : C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(OUT) :: SHT_crv
            type(C_PTR) SHT_rv
        end function c_class1_new

        subroutine c_class1_set_strings(self) &
                bind(C, name="TUT_tutorial_Class1_set_strings")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_set_strings

        subroutine c_class1_printvalues(self) &
                bind(C, name="TUT_tutorial_Class1_printvalues")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_printvalues

        function c_class1_get_int_ptr(self, len) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get_int_ptr")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            integer(C_INT), intent(OUT) :: len
            type(C_PTR) SHT_rv
        end function c_class1_get_int_ptr

        function c_class1_get_int_ptr_bufferify(self, DSHC_rv, len) &
                result(SHT_rv) &
                bind(C, name="TUT_tutorial_Class1_get_int_ptr_bufferify")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_array, SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(SHROUD_array), intent(INOUT) :: DSHC_rv
            integer(C_INT), intent(OUT) :: len
            type(C_PTR) SHT_rv
        end function c_class1_get_int_ptr_bufferify

        subroutine c_class1_get_strs(self, strs, name_len) &
                bind(C, name="TUT_tutorial_Class1_get_strs")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(INOUT) :: strs
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_get_strs

        subroutine c_class1_get_strs_bufferify(self, strs, name_len) &
                bind(C, name="TUT_tutorial_Class1_get_strs_bufferify")
            use iso_c_binding, only : C_INT, C_PTR
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
            type(C_PTR), intent(INOUT) :: strs
            integer(C_INT), value, intent(IN) :: name_len
        end subroutine c_class1_get_strs_bufferify

        subroutine c_class1_delete(self) &
                bind(C, name="TUT_tutorial_Class1_delete")
            import :: SHROUD_class1_capsule
            implicit none
            type(SHROUD_class1_capsule), intent(IN) :: self
        end subroutine c_class1_delete

        ! splicer begin namespace.tutorial.class.Class1.additional_interfaces
        ! splicer end namespace.tutorial.class.Class1.additional_interfaces

        ! splicer begin namespace.tutorial.additional_interfaces
        ! splicer end namespace.tutorial.additional_interfaces
    end interface

    interface class1
        module procedure class1_new
    end interface class1

contains

    function class1_new() &
            result(SHT_rv)
        use iso_c_binding, only : C_PTR
        type(class1) :: SHT_rv
        ! splicer begin namespace.tutorial.class.Class1.method.new
        type(C_PTR) :: SHT_prv
        SHT_prv = c_class1_new(SHT_rv%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.new
    end function class1_new

    subroutine class1_set_strings(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.set_strings
        call c_class1_set_strings(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.set_strings
    end subroutine class1_set_strings

    subroutine class1_printvalues(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.printvalues
        call c_class1_printvalues(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.printvalues
    end subroutine class1_printvalues

    function class1_get_int_ptr(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT, C_PTR, c_f_pointer
        class(class1) :: obj
        type(SHROUD_array) :: DSHC_rv
        integer(C_INT) :: len
        integer(C_INT), pointer :: SHT_rv(:)
        ! splicer begin namespace.tutorial.class.Class1.method.get_int_ptr
        type(C_PTR) :: SHT_ptr
        SHT_ptr = c_class1_get_int_ptr_bufferify(obj%cxxmem, DSHC_rv, &
            len)
        call c_f_pointer(SHT_ptr, SHT_rv, DSHC_rv%shape(1:1))
        ! splicer end namespace.tutorial.class.Class1.method.get_int_ptr
    end function class1_get_int_ptr

    subroutine class1_get_strs(obj, strs)
        use iso_c_binding, only : C_F_POINTER, C_INT, C_LOC
        class(class1) :: obj
        character(len=*), intent(INOUT), pointer :: strs(:)
        integer(C_INT) :: name_len
        ! splicer begin namespace.tutorial.class.Class1.method.get_strs
        type(C_PTR) cstr
        cstr = C_LOC(strs)
        call c_class1_get_strs_bufferify(obj%cxxmem, cstr, name_len)
        call C_F_POINTER(cstr,strs,[2])
        print*,strs(1),strs(2),name_len
        ! splicer end namespace.tutorial.class.Class1.method.get_strs
    end subroutine class1_get_strs

    subroutine class1_delete(obj)
        class(class1) :: obj
        ! splicer begin namespace.tutorial.class.Class1.method.delete
        call c_class1_delete(obj%cxxmem)
        ! splicer end namespace.tutorial.class.Class1.method.delete
    end subroutine class1_delete

    ! Return pointer to C++ memory.
    function class1_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(class1), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function class1_get_instance

    subroutine class1_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(class1), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine class1_set_instance

    function class1_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(class1), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function class1_associated

    ! splicer begin namespace.tutorial.class.Class1.additional_functions
    ! splicer end namespace.tutorial.class.Class1.additional_functions

    ! splicer begin namespace.tutorial.additional_functions
    ! splicer end namespace.tutorial.additional_functions

    function class1_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_eq

    function class1_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(class1), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function class1_ne

end module tutorial_tutorial_mod
